export interface ImageMediaSeed {
  type: "SLIDER" | "BANNER";
  position: "HOME_TOP" | "BELOW_SLIDER" | "HOME_SECTION_1" | "HOME_SECTION_2";
  title?: string;
  imagePath: string;
  linkUrl?: string; // slug của sản phẩm / bài viết / trang (nếu có)
  order: number;
  isActive?: boolean;
}

export const imageMediaSeeds: ImageMediaSeed[] = [
  // SLIDER - Trang chủ trên cùng (thường 3-5 slide)
  {
    type: "SLIDER",
    position: "HOME_TOP",
    title: "banner - bg-tet-1",
    imagePath: "sliders/bg-tet-1.webp",
    linkUrl: "/khuyen-mai-tet-1",
    order: 1,
    isActive: true,
  },
  {
    type: "SLIDER",
    position: "HOME_TOP",
    title: "banner - bg-tet-2",
    imagePath: "sliders/bg-tet-2.webp",
    linkUrl: "/khuyen-mai-tet-2",
    order: 2,
    isActive: true,
  },
  {
    type: "SLIDER",
    position: "HOME_TOP",
    title: "banner - slider-1",
    imagePath: "sliders/slider-1.webp",
    linkUrl: "/uu-dai-slider-1",
    order: 3,
    isActive: true,
  },
  {
    type: "SLIDER",
    position: "HOME_TOP",
    title: "banner - slider-2",
    imagePath: "sliders/slider-2.webp",
    linkUrl: "/uu-dai-slider-2",
    order: 4,
    isActive: true,
  },

  // --- BANNER (BELOW_SLIDER: banner-1 -> banner-7) ---
  {
    type: "BANNER",
    position: "BELOW_SLIDER",
    title: "banner - 1",
    imagePath: "banner/banner-1.webp",
    linkUrl: "/landing-page-1",
    order: 1,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "BELOW_SLIDER",
    title: "banner - 2",
    imagePath: "banner/banner-2.webp",
    linkUrl: "/landing-page-2",
    order: 2,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "BELOW_SLIDER",
    title: "banner - 3",
    imagePath: "banner/banner-3.webp",
    linkUrl: "/landing-page-3",
    order: 3,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "BELOW_SLIDER",
    title: "banner - 4",
    imagePath: "banner/banner-4.webp",
    linkUrl: "/landing-page-4",
    order: 4,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "BELOW_SLIDER",
    title: "banner - 5",
    imagePath: "banner/banner-5.webp",
    linkUrl: "/landing-page-5",
    order: 5,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "BELOW_SLIDER",
    title: "banner - 6",
    imagePath: "banner/banner-6.webp",
    linkUrl: "/landing-page-6",
    order: 6,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "BELOW_SLIDER",
    title: "banner - 7",
    imagePath: "banner/banner-7.webp",
    linkUrl: "/landing-page-7",
    order: 7,
    isActive: true,
  },

  // --- HOME_SECTION_1 (banner-8 -> banner-21) ---
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 8",
    imagePath: "banner/banner-8.webp",
    linkUrl: "/khuyen-mai-8",
    order: 1,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 9",
    imagePath: "banner/banner-9.webp",
    linkUrl: "/khuyen-mai-9",
    order: 2,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 10",
    imagePath: "banner/banner-10.webp",
    linkUrl: "/khuyen-mai-10",
    order: 3,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 11",
    imagePath: "banner/banner-11.webp",
    linkUrl: "/khuyen-mai-11",
    order: 4,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 12",
    imagePath: "banner/banner-12.webp",
    linkUrl: "/khuyen-mai-12",
    order: 5,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 13",
    imagePath: "banner/banner-13.webp",
    linkUrl: "/khuyen-mai-13",
    order: 6,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 14",
    imagePath: "banner/banner-14.webp",
    linkUrl: "/khuyen-mai-14",
    order: 7,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 15",
    imagePath: "banner/banner-15.webp",
    linkUrl: "/khuyen-mai-15",
    order: 8,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 16",
    imagePath: "banner/banner-16.webp",
    linkUrl: "/khuyen-mai-16",
    order: 9,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 17",
    imagePath: "banner/banner-17.webp",
    linkUrl: "/khuyen-mai-17",
    order: 10,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 18",
    imagePath: "banner/banner-18.webp",
    linkUrl: "/khuyen-mai-18",
    order: 11,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 19",
    imagePath: "banner/banner-19.webp",
    linkUrl: "/khuyen-mai-19",
    order: 12,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 20",
    imagePath: "banner/banner-20.webp",
    linkUrl: "/khuyen-mai-20",
    order: 13,
    isActive: true,
  },
  {
    type: "BANNER",
    position: "HOME_SECTION_1",
    title: "banner - 21",
    imagePath: "banner/banner-21.webp",
    linkUrl: "/khuyen-mai-21",
    order: 14,
    isActive: true,
  },
];
